const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ORG_ADMIN: 'ORG_ADMIN',
  FINANCE_MANAGER: 'FINANCE_MANAGER',
  HR_MANAGER: 'HR_MANAGER',
  EMPLOYEE: 'EMPLOYEE',
};

const BUDGET_STATUS = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
};

const VERSION_STATUS = {
  DRAFT: 'DRAFT',
  FINAL: 'FINAL',
  LOCKED: 'LOCKED',
};

const SCENARIO_TYPES = {
  BASELINE: 'BASELINE',
  BEST_CASE: 'BEST_CASE',
  WORST_CASE: 'WORST_CASE',
  CUSTOM: 'CUSTOM',
};

const ASSUMPTION_TYPES = {
  REVENUE_GROWTH: 'REVENUE_GROWTH',
  COST_GROWTH: 'COST_GROWTH',
  HEADCOUNT_CHANGE: 'HEADCOUNT_CHANGE',
  SALARY_INCREMENT: 'SALARY_INCREMENT',
  ATTRITION_RATE: 'ATTRITION_RATE',
  BONUS_PERCENT: 'BONUS_PERCENT',
  CUSTOM: 'CUSTOM',
};

const FORECAST_PERIODS = {
  MONTHLY: 'MONTHLY',
  QUARTERLY: 'QUARTERLY',
  YEARLY: 'YEARLY',
};

const INSIGHT_TYPES = {
  BUDGET: 'BUDGET',
  SCENARIO: 'SCENARIO',
  PAYROLL: 'PAYROLL',
  FORECAST: 'FORECAST',
  WORKFORCE: 'WORKFORCE',
  KPI: 'KPI',
};

module.exports = {
  USER_ROLES,
  BUDGET_STATUS,
  VERSION_STATUS,
  SCENARIO_TYPES,
  ASSUMPTION_TYPES,
  FORECAST_PERIODS,
  INSIGHT_TYPES,
};